export const ROUTES = {
    Home : "/",
    Soul : "/soul",
    Body : "/body",
    Mind : "/mind",
    Romance : "/romance",
    Family : "/family",
    Friends : "/friends",
    Mission : "/mission",
    Money : "/money",
    Growth : "/growth",
    Joy : "/joy",
    Wheel : "/wheel",
    Login : "/login",
    SignUp : "/signup",
    AllWheels : "/allwheels",
    Profile : "/profile",
    ChangePassword:"/changepassword",
    ForgotPassword : "/forgotpassword",
    ResetPassword : "/resetpassword",

}