FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package*.json ./

COPY . .

RUN npm run build

# Use a lightweight server to serve the build files
FROM nginx:alpine

# Copy the build files from the previous stage
COPY --from=0 /usr/src/app/build /usr/share/nginx/html

# Expose the port the server runs on
EXPOSE 80

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]